Repository North-Seattle-College/ad440-winter2021-thursday-repo, pull requests merged in 2021-01, with the labels that each got.

#8 Task7 azurestoragescript
  Automation/.gitignore
  Automation/create_Azure_StorageAccount.ps1
Labels: team2

#39 GH Action workflow to start performance test with slsart
  .github/workflows/performancetest.yml
Labels: team3

#48 GitHub Actions auto-deploy azure functions
  .github/workflows/deployAzureFunctions.yaml
  .gitignore
Labels: team1

#50 Should fix a bug caused by incorrect file paths
  .github/workflows/deployAzureFunctions.yaml
Labels: bug, team1

#29 Feature/team1 task6 issue17 implement sql
  sql/dbschema.sql
Labels: task, team1

#49 Feature/task12 azure function usersId
  .gitignore
  Automation/.gitignore
  Automation/create_Azure_StorageAccount.ps1
  functions/.funcignore
  functions/.gitignore
  functions/HttpTriggerAPIUsersId/__init__.py
  functions/HttpTriggerAPIUsersId/function.json
  functions/HttpTriggerAPIUsersId/sample.dat
  functions/host.json
  functions/proxies.json
  functions/requirements.txt
Labels: team1

#59 Implement azure function endpoint to fetch all users
  .gitignore
  functions/.gitignore
  functions/HttpTriggerAPIUsers/__init__.py
  functions/HttpTriggerAPIUsers/function.json
  functions/HttpTriggerAPIUsersId/sample.dat
  functions/requirements.txt
Labels: team1

#61 Natalia issue6 temp
  .gitignore
  functions/.gitignore
  functions/HttpTriggerAPIUsersIdTaskId/__init__.py
  functions/HttpTriggerAPIUsersIdTaskId/function.json
  functions/requirements.txt
Labels: task, team1

#47 Yaholl/issue 16 vnet script
  Automation/login.ps1
  Automation/vnet/create_vnet.ps1
  Automation/vnet/vnet_template.json
Labels: team3

#78 [BUG] Finished implementing the react UI (from Sprint 1)
  ui/react-ui/.gitignore
  ui/react-ui/README.md
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/public/favicon.ico
  ui/react-ui/public/index.html
  ui/react-ui/public/logo192.png
  ui/react-ui/public/logo512.png
  ui/react-ui/public/manifest.json
  ui/react-ui/public/robots.txt
  ui/react-ui/src/App.css
  ui/react-ui/src/App.js
  ui/react-ui/src/App.test.js
  ui/react-ui/src/index.css
  ui/react-ui/src/index.js
  ui/react-ui/src/logo.svg
  ui/react-ui/src/reportWebVitals.js
  ui/react-ui/src/setupTests.js
Labels: bug, team1

#40 Feature/toddys examples
  example/automation-example/function-automation/deploy-template.ps1
  example/automation-example/function-automation/deploy-template.sh
  example/automation-example/function-automation/parameters.json
  example/automation-example/function-automation/template.json
  example/functions-example/.funcignore
  example/functions-example/.gitignore
  example/functions-example/HttpTriggerToddysmExample/__init__.py
  example/functions-example/HttpTriggerToddysmExample/function.json
  example/functions-example/HttpTriggerToddysmExample/sample.dat
  example/functions-example/host.json
  example/functions-example/proxies.json
  example/functions-example/requirements.txt
Labels: team1

#62 Created ARM Template script that creates Azure function
  Automation/create_Azure_Function_Task_3.json
Labels: team2

#81 Complete implementation of Azure function for /users endpoint - Task 76
  functions/HttpTriggerAPIUsers/__init__.py
  functions/HttpTriggerAPIUsers/function.json
Labels: task, team1

#46 Deploy UI code to Azure (Storage) when PR is complete (GH Actions)
  .github/workflows/AzureDeploy.yml
  .gitignore
Labels: team3

#97 Feature/issue79 team1 sprint2 add user tasks route
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/public/favicon.ico
  ui/react-ui/public/index.html
  ui/react-ui/public/logo192.png
  ui/react-ui/public/logo512.png
  ui/react-ui/public/manifest.json
  ui/react-ui/src/App.css
  ui/react-ui/src/App.js
  ui/react-ui/src/App.test.js
  ui/react-ui/src/components/app/App.css
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/bootstrapTable/BootstrapTable.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/userTasks/UserTasks.js
  ui/react-ui/src/index.js
  ui/react-ui/src/logo.svg
Labels: task, team1

#89 Feature/team1 issue71 complete azure users user id function
  functions/HttpTriggerAPIUsersId/__init__.py
  functions/HttpTriggerAPIUsersId/function.json
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/public/index.html
  ui/react-ui/public/manifest.json
  ui/react-ui/src/components/app/App.css
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/index.js
Labels: bug, task, team1

#103 Feature/team1 issue67 reactpage users
  .gitignore
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/public/index.html
  ui/react-ui/public/manifest.json
  ui/react-ui/src/components/app/App.css
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/userTasks/UserTasks.js
  ui/react-ui/src/components/routes/users/Users.js
  ui/react-ui/src/index.js
Labels: task, team1

#82 deployment of Resource group, function app, storage account and application service plan
  Automation/task2/team2/deployment.ps1
  Automation/task2/team2/template.json
  example/myscript.py
Labels: task, team2
