Repository North-Seattle-College/ad440-winter2021-thursday-repo, pull requests merged in 2021-02, with the labels that each got.

#88 [BUG] users/userId/tasks/taskId API logging and error handling Issue #83
  functions/HttpTriggerAPIUsersIdTaskId/__init__.py
  functions/HttpTriggerAPIUsersIdTaskId/function.json
Labels: bug, task, team1

#107 Feature/task03/completeUserId/tasks_function
  .gitignore
  functions/.gitignore
  functions/HttpTriggerAPIUsersIdTask/__init__.py
  functions/HttpTriggerAPIUsersIdTask/function.json
Labels: bug, task, team1

#112 UserID endpoint UI
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/bootstrapTable/BootstrapTable.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/userid/userid.js
Labels: task, team1

#115 Get the artillery results from S3 bucket and render in React for /users/{user_id}
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/reports/userIdReport/UserIdReport.js
Labels: task, team3

#108 Bug/team1 issue102 fix users/{userId}/tasks url
  ui/react-ui/package-lock.json
  ui/react-ui/package.json
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/bootstrapBackButton/BootstrapBackButton.js
  ui/react-ui/src/components/bootstrapTable/BootstrapTable.js
  ui/react-ui/src/components/routes/home/Home.css
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/userTasks/UserTasks.js
  ui/react-ui/src/components/routes/userid/userid.js
  ui/react-ui/src/components/routes/users/Users.js
Labels: bug, team1

#113 Create Login Module
  Automation/Login/Login.psm1
  Automation/login.ps1
  Automation/public_ip/create_ip_address.ps1
  Automation/public_ip/public_ip_template.json
  Automation/task2/team2/deployment.ps1
  Automation/vnet/create_vnet.ps1
Labels: bug, team3

#109 Automate Alert Rule Creation
  Automation/alert/alert_template.json
  Automation/alert/create_alert.ps1
  Automation/vnet/create_vnet.ps1
Labels: task, team3

#123 [BUG] Feature HttpTriggerAPIUsers/{UserId} DB error
  functions/HttpTriggerAPIUsersId/__init__.py
  functions/requirements.txt
Labels: bug, team1

#104 React UI that displays all artillery results for /users API
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/reports/usersReport/UserReport.js
Labels: task, team3

#117 Issue#101 testresults users/userid/tasks/taskid
  ui/react-ui/package.json
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/reports/taskIdReport/TaskIdReport.js
Labels: task, team2

#120 Issue 94 React user task page
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/userSingleTask/UserSingleTask.js
Labels: team3

#69 Feature/task1 automation users api
  automation/usersAPI/deploy-users-templet.ps1
  automation/usersAPI/template.json
Labels: team2

#126 Perf test users/{user id} issue#73
  .github/workflows/performancetest-users-userID.yaml
  test/artillery/performanceScript-users-userID.yaml
  test/results/results.json
Labels: team4

#57 Alexsuth/issue 22 vm script
  .gitignore
  Automation/vm.json
  Automation/vm/create_vm_script.ps1
  Automation/vm/ubuntu_vm_parameters.json
Labels: team3

#136 Complete automation of ARM template and removing user interactivity (added Login module)
  Automation/FunctionAppUsersUserID/script.ps1
  Automation/FunctionAppUsersUserID/template.json
Labels: team2

#121 Task34 create storage account script
  Automation/StorageAccount/.gitignore
  Automation/StorageAccount/create_Azure_StorageAccount.ps1
  Automation/StorageAccount/template.json
Labels: bug, task, team2

#119 [Task] Get the artillery results from S3 bucket and render in React for /users/{user_id}/tasks
  ui/react-ui/package.json
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/reports/userIdReport/UserIdTasksReport.js
Labels: team3

#60 Issue 31 sql server ARM template and script
  Automation/SQL/azureDeploy.json
  Automation/SQL/azureDeploy.ps1
Labels: team3

#156 ARM Script to Create SQL Resources with Approved Naming Convention and Tags
  Automation/SQL/azureDeploy.json
  Automation/SQL/azureDeploy.ps1
Labels: task, team1

#142 ARM Template Create Resources For Functions (Function App, AppService Plan, AppInsights, and Storage Account)
  Automation/functionappResourceCreationScript/deploy_template_functionapp.ps1
  Automation/functionappResourceCreationScript/template.json
Labels: bug, task, team1

#139 GitHub action to deploy functions to the new function app
  .github/workflows/deploy-apis.yaml
  functions/HttpTriggerAPIUsersId/__init__.py
Labels: task, team1

#158 Feature/team1 issue130 key vault script
  Automation/azKeyVault/deployment.ps1
  Automation/azKeyVault/template.json
  Automation/azKeyVault/template.parameters.json
Labels: task, team1

#129 [Task] Create and Deploy Serverless Artillery test for /Users/{UserID}/Tasks/{TaskID}
  .gitignore
  package-lock.json
  test/artillery/.slsart
  test/artillery/alert.js
  test/artillery/analysis.js
  test/artillery/artillery-acceptance.js
  test/artillery/artillery-monitoring.js
  test/artillery/artillery-performance.js
  test/artillery/artillery-task.js
  test/artillery/handler.js
  test/artillery/modes.js
  test/artillery/package.json
  test/artillery/perf-test-artillery.yaml
  test/artillery/planning.js
  test/artillery/platform-settings.js
  test/artillery/sampling.js
  test/artillery/serverless.yml
  ui/react-ui/package-lock.json
Labels: team4

#159 Pull request for merging AWS S3 Bucket template into development
  Automation/S3BucketTemplate/s3_bucket_template.json
Labels: task, team2

#172 Feature issue#150 GitHub action serverless artillery test users
  .github/workflows/serverless-artillery-test-users-api.yml
  package-lock.json
  package.json
  test/artillery/performance-test-user.yml
  test/aws/aws-deploy.js
  test/results/serverless-artillery-test-users-api.json
  test/serverless-artillery/serverless-artillery-test-users-api.yml
Labels: task, team1

#180 Fix the s3 upload for users serverless artillery test
  .github/workflows/serverless-artillery-test-users-api.yml
  test/aws/aws-deploy.js
Labels: Work-in-Progress, bug, task, team1

#170 Redis Caching for /users
  functions/HttpTriggerAPIUsers/__init__.py
  functions/requirements.txt
Labels: task, team3

#163 GitHub Action to Test users/user_id/tests/test_id
  .github/workflows/artillery-action-users-id-tasks-id.yaml
  scripts/artillery-python-users-id-tasks-id.py
  scripts/artillery-shell-users-id-tasks-id.sh
  test/artillery/artillery-test-users-id-tasks-id-api.yaml
Labels: team3

#184 Redis Cache users/userID/tasks and Perf Test Fixes
  .github/workflows/performancetest-users-userID.yaml
  functions/HttpTriggerAPIUsersIdTask/__init__.py
  test/artillery/performanceScript-users-userID.yaml
Labels: task, team4

#162 Sg refactor react UI - Fetch data from Azure FunctionsApp API
  .gitignore
  ui/react-ui/.gitignore
  ui/react-ui/src/components/PageTitle/PageTitle.js
  ui/react-ui/src/components/routes/userSingleTask/UserSingleTask.js
  ui/react-ui/src/components/routes/userTasks/UserTasks.js
  ui/react-ui/src/components/routes/userid/userid.js
  ui/react-ui/src/utils.js
Labels: task, team4

#179 github action for artillery test on endpoint /users/{user_id}/tasks
  .github/workflows/artillery-test-users-user_id-tasks.yaml
  test/artillery/artillery-perf-test-users-user_id-tasks.yaml
  test/results/artillery-test-users-user_id-tasks-results.json
Labels: team3

#167 Create deletion script for S3 buckets - task154
  .gitignore
  Automation/S3/delete_s3_buckets.py
  Automation/S3/requirements.txt
Labels: team1

#168 Prototype Azure function to access Redis cache
  prototypes/functions/HttpTriggerRedis/function.json
  prototypes/functions/HttpTriggerRedis/prototype-redis-cache-connect.py
  prototypes/functions/HttpTriggerRedis/sample.dat
Labels: task, team3

#169 adds automation for creating Redis-cache
  Automation/Redis_Cache/deploy.ps1
  Automation/Redis_Cache/template.json
Labels: team3

#213 Fix Deployment of Functions
  .github/workflows/deploy-apis.yaml
  functions/HttpTriggerAPIUsersId/__init__.py
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: task, team3

#181 Changed GitHub action for Artillery to test the new function /users
  .github/workflows/artillery-action-users-api.yml
  test/artillery/artillery-test-users-api.yml
Labels: task, team2

#211 fix the dploy-ui action bug
  .github/workflows/deploy-ui.yml
Labels: bug, team1

#198 React UI for Creating User
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/create/Create.css
  ui/react-ui/src/components/routes/create/Create.js
  ui/react-ui/src/components/routes/home/Home.js
Labels: team3
