Repository North-Seattle-College/ad440-winter2021-thursday-repo, pull requests merged in 2021-03, with the labels that each got.

#216 fix the bug in HttpTriggerAPIUsersIdTask (users/userId/tasks) function
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: bug, team1

#221 Bug/fix bugs in users userid function + redis
  functions/HttpTriggerAPIUsersId/__init__.py
Labels: bug, team1

#222 Slsart users api test
  .github/workflows/serverless-artillery-test-users-api.yml
  test/aws/aws-deploy.js
Labels: task, team1

#224 Add UI test for /users of the React page
  .github/workflows/ui-tests-users.yaml
  test/results/ui-test-results/users/README.txt
  test/ui/package.json
  test/ui/ui-tests-user.js
Labels: task, team1

#215 sql injection test for post users/userid/tasks
  .github/workflows/serverless-artillery-test-users-api.yml
  .github/workflows/sql-injection-post-users-userid-tasks.yml
Labels: task, team1

#218 Redis Expire on get + rDB bug + redisfeatureflag
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: task, team4

#223 Caching Feature Flag for /users
  automation/.gitignore
  automation/FunctionAppUsersUserID/script.ps1
  automation/FunctionAppUsersUserID/template.json
  automation/Login/Login.psm1
  automation/NSG/deploy-nsg.ps1
  automation/NSG/template.json
  automation/Redis_Cache/deploy.ps1
  automation/Redis_Cache/template.json
  automation/S3/delete_s3_buckets.py
  automation/S3/requirements.txt
  automation/S3BucketTemplate/s3_bucket_template.json
  automation/SQL/azureDeploy.json
  automation/SQL/azureDeploy.ps1
  automation/StorageAccount/.gitignore
  automation/StorageAccount/create_Azure_StorageAccount.ps1
  automation/StorageAccount/template.json
  automation/Task4/deploy_template_task4.ps1
  automation/Task4/template.json
  automation/Task6/AppGateway.ps1
  automation/Task6/template.json
  automation/alert/alert_template.json
  automation/alert/create_alert.ps1
  automation/azKeyVault/deployment.ps1
  automation/azKeyVault/template.json
  automation/azKeyVault/template.parameters.json
  automation/functionappResourceCreationScript/deploy_template_functionapp.ps1
  automation/functionappResourceCreationScript/template.json
  automation/public_ip/create_ip_address.ps1
  automation/public_ip/public_ip_template.json
  automation/task2/team2/deployment.ps1
  automation/task2/team2/template.json
  automation/vm.json
  automation/vm/create_vm_script.ps1
  automation/vm/ubuntu_vm_parameters.json
  automation/vnet/create_vnet.ps1
  automation/vnet/vnet_template.json
  functions/HttpTriggerAPIUsers/__init__.py
  functions/HttpTriggerAPIUsersIdTaskId/__init__.py
Labels: task, team3

#234 Sql injection user userid test
  .github/workflows/sql-injection-put-users-userid.yml
  test/security/sql-injection/sql-injection-users-userid-put.json
Labels: task, team1

#232 UI Test for /users/userid/tasks/taskid
  .github/workflows/ui-test-users-id-tasks-id.yml
  test/results/ui-test-results/users-id-tasks-id/README.TXT
  test/ui/package.json
  test/ui/ui-test-users-id-tasks-id.js
Labels: task, team1

#230 Fix script for key vault and use object params
  Automation/azKeyVault/create_kv_with_param_files/deployment.ps1
  Automation/azKeyVault/create_kv_with_param_files/template.json
  Automation/azKeyVault/create_kv_with_param_files/template.parameters.json
  Automation/azKeyVault/create_kv_with_param_objects/deployment.ps1
  Automation/azKeyVault/create_kv_with_param_objects/template.json
Labels: bug, task, team1

#246 Resolve duplicate folders
  automation/azKeyVault/create_kv_with_param_files/deployment.ps1
  automation/azKeyVault/create_kv_with_param_files/template.json
  automation/azKeyVault/create_kv_with_param_files/template.parameters.json
  automation/azKeyVault/create_kv_with_param_objects/deployment.ps1
  automation/azKeyVault/create_kv_with_param_objects/template.json
Labels: bug, team1

#226 Web UI test for users/{user-id} and upload results to Azure storage.
  .github/workflows/ui-tests-users-id.yml
  test/ui/ui-tests-user-id.js
Labels: task, team3

#235 SQL injection test for PUT on sql-injection/users/userid/tasks/taskid
  .github/workflows/sql-injection-put-users-userid-tasks-taskid.yml
Labels: task, team3

#255 /users API for AWS - Task 248
  aws-functions/HttpTriggerAPIUsers/lambda_function.py
Labels: task, team1

#173 [ Task ] Implementing caching in the /users/{user_id}/tasks/{task_id} (GET, PUT, DELETE) Invalidate users:{user_id}/tasks/{task_id}’ on PUT, DELETE.
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  functions/HttpTriggerAPIUsersIdTaskId/__init__.py
  package-lock.json
  package.json
Labels: task, team4

#228 SQL injection DELETE test for /users/{user_id}
  .github/workflows/sql-injection-delete-users-userid.yml
  test/security/sql-injection/delete-users-userid.json
Labels: team3

#257 Implemented react pagination for /users
  ui/react-ui/package.json
  ui/react-ui/src/components/app/App.css
  ui/react-ui/src/components/app/App.js
  ui/react-ui/src/components/routes/users/UsersPaginated.js
  ui/react-ui/src/index.js
Labels: task, team3

#252 create AWS RDS
  sql/dbschema.sql
Labels: task, team1

#265 /users/{userId}/tasks Pagination
  functions/HttpTriggerAPIUsers/__init__.py
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: task, team3

#270 Implement Delete User From All Users Page via Delete Option
  functions/HttpTriggerAPIUsersId/__init__.py
  ui/react-ui/.vscode/launch.json
  ui/react-ui/src/components/routes/users/Users.js
Labels: task, team1

#275 GH Action - Artillery test on AWS Lambda User function and upload to Azure Storage
  .github/workflows/artillery-lambda-users-api.yml
  test/artillery/artillery-test-lambda-users.yml
  test/artillery/payloads/usersPayload.csv
Labels: team3

#268 AWS lambda function users userid
  aws-functions/HttpTriggerAPIUsersUserId/lambda_function.py
Labels: task, team1

#274 Lambda function of Users/{UserId}/tasks
  aws-functions/HttpTriggerApiUsersUseridTasks/lambda_function.py
Labels: task, team1

#277 removed merge conflict remnants
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: bug, team3

#281 Fix the home page and implement the links
  ui/react-ui/src/components/app/App.css
  ui/react-ui/src/components/routes/home/Home.css
  ui/react-ui/src/components/routes/home/Home.js
  ui/react-ui/src/components/routes/home/collaborating.png
Labels: task, team1

#284 Implemented taskId aws function
  aws-functions/HttpTriggerApiTaskId/lambda_function.py
Labels: task, team1

#291 Delete User on UsersPaginated
  ui/react-ui/package.json
  ui/react-ui/src/components/routes/users/ConfirmDeleteUserModal.js
  ui/react-ui/src/components/routes/users/ToastMessage.js
  ui/react-ui/src/components/routes/users/Users.js
  ui/react-ui/src/components/routes/users/UsersPaginated.js
Labels: bug, team1

#269 As/swagger documentation
  docs/swagger.yaml
Labels: task, team3

#244 Pagination for Users + Users/UserID/Tasks Environ fix
  functions/.gitignore
  functions/.vscode/extensions.json
  functions/.vscode/launch.json
  functions/.vscode/settings.json
  functions/.vscode/tasks.json
  functions/HttpTriggerAPIUsers/__init__.py
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: task, team4

#276 CloudFormation RDS Deploy Script
  Automation/RDS/deploy.py
Labels: team3

#286 changed CACHE_TOGGLE from On/Off to true/false
  functions/HttpTriggerAPIUsersIdTask/__init__.py
Labels: bug, team3

#303 /Users API returning tasks instead of users, querying redis cache incorrectly
  functions/HttpTriggerAPIUsers/__init__.py
  package-lock.json
  package.json
Labels: bug

#317 Capture average time to load /users/{userId} with cache
  .gitignore
  package-lock.json
  test/ui/package.json
  test/ui/time-users-id.js
  ui/react-ui/src/index.js
Labels: task, team3

#323 Added function to count how long it takes to load a page 40 times
  test/ui/capturetimetaskid.js
Labels: task, team4

#297 Sg run UI tests
  .DS_Store
  .github/workflows/ui-tests.yaml
  .gitignore
  .vscode/extensions.json
  test/artillery/Artillery-test-users-user_id-tasks.yml
  test/results/ui-test-results/ui-performance-2021-03-22T05:56:34.598Z.json
  test/results/ui-test-results/ui-performance-2021-03-22T18:30:12.808Z.json
  test/results/ui-test-results/ui-performance-2021-03-23T19:02:53.330Z.json
  test/results/ui-test-results/ui-performance-2021-03-25T04:43:25.149Z.json
  test/ui/jsconfig.json
  test/ui/package.json
  test/ui/run-ui-tests.js
  test/ui/ui-test-tasks.js
  test/ui/ui-tests-user.js
  ui/react-ui/src/components/routes/home/Home.js
Labels: task, team4
